### ISSUE TITLE
Unable to load predictions from GitHub

### ISSUE THREAD

**Issue by martinlingstuyl** [anoopt/PnP.PowerShell.Predictor#1]
Hi Anoop,

Lately I've been receiving the following warning when launching new PowerShell windows;

`WARNING: Unable to load predictions from GitHub. Loading suggestions from local file. Hence some commands from the predictions might not work. Press enter to continue.`

I've narrowed it down and the suspect appears to be the PnP PowerShell Predictor. Any idea whats going on there?

![image](https://user-images.githubusercontent.com/5267487/218041213-54ab7623-4fdd-4ece-b449-90ac5019f86b.png)

**Comment by martinlingstuyl** [comment]
Hi @anoopt, did you have a chance to look at this error? I'm getting it all the time :-)

**Comment by anoopt** [comment]
Hi @martinlingstuyl apologies for the delayed response. Do you still see the error with the latest version of the PnP PowerShell predictor module?

**Comment by anoopt** [comment]
Also @martinlingstuyl we are now updating the code for predictors here - https://github.com/pnp/predictors

**Comment by martinlingstuyl** [comment]
Ah, version 1.1.1 fixes it indeed 😅 ought to have updated it first. I'll close this issue!

**Comment by martinlingstuyl** [comment]
Maybe you should update the readme of this GH repo and point to the other repo?
